FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-devel

WORKDIR /workspace

COPY requirements.txt /workspace/
COPY app /workspace/app/
COPY .env /workspace/
COPY notebook.ipynb /workspace/

RUN apt-get update && apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --index-url https://pypi.org/simple -r requirements.txt
RUN pip uninstall -y torch torchvision torchaudio
RUN pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cu124 torch torchaudio torchvision

EXPOSE 8888 5000

#CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]
